blank_issues_enabled: true
contact_links:
  - name: 🤗 Question
    url: https://baraja.cz/kontakt
    about: If you have a question or are looking for advice, please create issue or contact our tech support 💬
